# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GY2jrSZ0BJvYkhlh7oloBx-Ib8lAx93
"""

import streamlit as st
import pandas as pd
import joblib

from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[2010, 150000], [2015, 100000], [2020, 50000]])
y = np.array([100000, 200000, 350000])
model = LinearRegression()
model.fit(X, y)

st.title("🚗 Egyptian Used Car Price Prediction (Demo)")

# إدخال البيانات
year = st.number_input("سنة الصنع", 1990, 2025, 2015)
km_driven = st.number_input("عدد الكيلومترات", 0, 500000, 100000)

# زرار التوقع
if st.button("توقع السعر"):
    input_data = np.array([[year, km_driven]])
    prediction = model.predict(input_data)[0]
    st.success(f"💰 السعر المتوقع: {prediction:,.0f} جنيه")